# Generated by Django 4.2 on 2023-05-01 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnСonfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='siteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Return',
        ),
        migrations.AddField(
            model_name='returnсonfirmation',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_returns', to='myapp.buy'),
        ),
        migrations.AddField(
            model_name='returnсonfirmation',
            name='siteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
