# Generated by Django 4.2 on 2023-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_returnсonfirmation_alter_buy_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnсonfirmation',
            name='siteUser',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
