# Generated by Django 4.2 on 2023-05-01 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_returnсonfirmation_siteuser_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnсonfirmation',
            name='siteUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='return_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
