# Generated by Django 4.2 on 2023-05-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_returnсonfirmation_siteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnсonfirmation',
            name='buy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_returns', to='myapp.buy'),
        ),
    ]
