# Generated by Django 4.2 on 2023-05-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_returnсonfirmation_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnсonfirmation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
