# Generated by Django 4.2 on 2023-05-02 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_buy_created_at_alter_product_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returnсonfirmation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
