# Generated by Django 4.2 on 2023-05-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_buy_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnСonfirmation',
            new_name='ReturnConfirmation',
        ),
    ]
