# Generated by Django 4.2 on 2023-05-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_returnсonfirmation_returnconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='returnconfirmation',
            name='siteUser',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='ReturnConfirmation',
        ),
    ]
