# Generated by Django 4.2 on 2023-05-09 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_buy_returnconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
