# Generated by Django 4.2 on 2023-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_siteuser_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='summ',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
