# Generated by Django 4.2 on 2023-05-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_buy_summ_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_product', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='returnconfirmation',
            name='buy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returns_buys', to='myapp.buy'),
        ),
    ]
